### ISSUE TITLE
Can't use GHC >= 7.10

### ISSUE THREAD

**Issue by awson** [tim-m89/Salsa#7]
Did anybody try to ask GHC people about this? I can't find any tickets or discussions related. Any references?

**Comment by tim-m89** [comment]
Within the first few lines of stack.yaml there is this:

```
# Unfortunately, ghc versions >= 7.10 currently blow up the type checker when trying to compile samples
# that use more than a few method overloads (Console.WriteLine has heaps hence helloworld cannot be compiled for example)
resolver: ghc-7.8.4
```

The issue is mainly down to how type families evaluate strictly so that `P && Q` actually evaluates both sides in many cases. The GHC team knows this and have so far at least put slight hacks in place to help alleviate the problem (note how there's 3 additional equations for both `&&` and `||` [here](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/base-4.9.0.0/Data-Type-Bool.html))

Feel free to try and see if it will compile nicely or if the issue still remains. When I get a chance, I want to experiment with other ways of doing this. In particular, I'm curious to whether a type checker plugin would be the way to go.

As to why it behaved ok on 7.8.4, I'm not too sure but I attempted to get the answer [here](https://www.reddit.com/r/haskell/comments/3yg685/ghc_type_level_union/cydbfkj)
